#!/usr/bin/env bash

export VENV_PATH="venv"
set -e

if ! python --version > /dev/null 2>&1; then
    echo "Please install Python 3."
    exit 1
fi

if [[ ! -f ${VENV_PATH} ]]; then
    python -m venv ${VENV_PATH}
fi

source "${VENV_PATH}/Scripts/activate"
pip install -r requirements.txt

python server/server.py
